name: supernova's blogs111111
url: https://www.baidu.com/ 
description: AAAAAAAAAAAAAAAAAAAA

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

permalink: /themes/:title/

gems: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
