name: supernova's blogs11111122222222222
url: https://domeself.github.io/supernova1/ 
description: AAAAAAAAAAAAAAAAAAAA

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
assets: /assets



#### Language
language: zh-CN    ## blog site languages: en, zh-CN, zh-TW, de



permalink: /themes/:title/

gems: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
